### PR TITLE
Update 2023-09-21-scaling-waku-a-progress-update.mdx

### PR DESCRIPTION
**Pull request by DeBelg**
Typo fix & change date to be synced to actual publish date

### CODE REVIEW

**Comment by DeBelg** [comment]
@jakubgs  small update can we push pls :))

**Comment by DeBelg** [comment]
Closing this request in favour for a new one with additional changes

**Comment by DeBelg** [comment]
Reopening this as the waves continued and suddenly other changes were not necessary accept this.

TL;DR this pr is relevant

**Comment by DeBelg** [comment]
Reopening this as the waves continued and suddenly other changes were not necessary to accept this.

TL;DR this pr is relevant

**Review by jakubgs — APPROVED** [review]

**Pull request merged**
