### PR TITLE
Roadmap Article

### PR DESCRIPTION
**Pull request by DeBelg**
Ready for review by Franck, not ready to be pushed yet to main. as Matt still needs to have a final copy review after Franck

### CODE REVIEW

**Comment by DeBelg** [comment]
@fryorcraken PR ready after copy updates. I did an initial visual check, and everything looks OK. Please verify on your local.

**Comment by fryorcraken** [comment]
https://dev-blog.waku.org/waku-roadmap

**Comment by fryorcraken** [comment]
@DeBelg some comments when checking the rendering:

> jump [directly to it here](https://hackmd.io/6Q_bHochRMOvTRXN0vCr5A?both#Waku-Network-Gen-0).

This points to hackmd instead of same post

> 
and all other images needs to be included in this repo

> We apply [Waku Relay](https://hackmd.io/@vac/main/%2FYYlZYBCURFyO_ZG1EiteWg#11WAKU2-RELAY-gossipsub)

Not sure it makes sense to use this link, maybe either point to [RFC](https://rfc.vac.dev/spec/11/) or  [docs](https://docs.waku.org/overview/concepts/protocols#relay)

> The [Waku Network Gen 0](https://dev-blog.waku.org/waku-roadmap#Waku-Network-Gen-0)

> [Epics](https://dev-blog.waku.org/waku-roadmap#Gen-0-Epic-Summaries-amp-Keys)

> and setup of[the 10k milestone](https://github.com/waku-org/pm/issues/12).

space missing after _of_

> Gen 0 Epic Summaries & Keys

Looks like I previously missed that but not sure I understand "Keys" here.

Incorrect link, in md, links to sections titles are lowercase. e.g.  https://dev-blog.waku.org/waku-roadmap#waku-network-gen-0

**Comment by fryorcraken** [comment]
`[Free and or paid traffic design](https://hackmd.io/@alrevuelta/rkqbPKaoo)`

@jm-clius @alrevuelta is that a good link to share? do we have somethign better?

**Comment by alrevuelta** [comment]
> @jm-clius @alrevuelta is that a good link to share? do we have somethign better?

That is a bit outdated, this one is more up to date https://github.com/waku-org/research/issues/10. Note though that with RLN there are still many unknowns on how tokenization can be done (eg RLN memberships). I wouldn't add it to a blog post until the idea is more mature and concrete.

**Pull request merged**
